#  curl -L -O https://raw.githubusercontent.com/elastic/beats/7.11/deploy/docker/filebeat.docker.yml

#filebeat.config:
#  modules:
#    path: ${path.config}/modules.d/*.yml
#    reload.enabled: false

#filebeat.modules:
#  - module: elasticsearch

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/becoming/modern-spring-boot.log.json
    json.keys_under_root: true
    json.overwrite_keys: true

setup.kibana:
  host: "kibana:5601"

#processors:
#  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'